### ISSUE TITLE
Hackensack-Meridien Developers Workshop: Feb 8-9, 2023

### ISSUE THREAD

**Issue by RinatS** [im-customers/hackensack-meridien#1]
Leave the comment with the following information:
- First Name/Last Name
- Role/Title
- Business Email Address

**Comment by RinatS** [comment]
Rinat Shagisultanov
Technical Director
rinats@infomagnus.com

**Comment by KeerthiKamma2022** [comment]
Keerthi Kamma 
Cloud Architect
keerthi.kamma@hmhn.org

**Comment by mjudge63** [comment]
Michael Judge - michael.judge@hmhn.org

**Comment by RinatS** [comment]
Cyril Nambangi - Cloud architect (cyril.nambangi@hmhn.org)
